## Read and Show Image

In [2]:
import cv2

In [8]:
# img = cv2.imread("vikas1.jpg")  # image read
# cv2.imshow("vikas_kasaudhan",img)   # image show with window name
# cv2.waitKey(10000)                   # image frame wait    time->ms   and 0->pass keyboard any key press
# cv2.destroyAllWindows()              # all window close
# #cv2.destroyWindow()                  # any one window close with window name

In [10]:
img = cv2.imread("vikas1.jpg")  # image read
cv2.imshow("vikas_kasaudhan",img)   # image show with window name
cv2.imshow("vikas_kasaudhan1",img)
cv2.waitKey(0)                   # image frame wait    time->ms   and 0->pass keyboard any key press
#cv2.destroyAllWindows()              # all window close
cv2.destroyWindow("vikas_kasaudhan1")                  # any one window close with window name

## Show Multiple Images and Slide Show

In [4]:
import cv2
import numpy as np

In [20]:
img = cv2.imread(r"D:\Project\project\Face_Recognition\ViaksKasaudhan\vikas1.jpeg")
re_img = cv2.resize(img,(500,400))
cv2.imshow("vikas",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
img = cv2.imread(r"D:\Project\project\Face_Recognition\ViaksKasaudhan\vikas1.jpeg")
print(img)  #RGB

[[[109 102  53]
  [111 104  55]
  [114 107  58]
  ...
  [244 227 206]
  [245 228 207]
  [245 228 207]]

 [[110 103  54]
  [112 105  56]
  [115 108  59]
  ...
  [244 227 206]
  [245 228 207]
  [245 228 207]]

 [[110 103  54]
  [112 105  56]
  [115 108  59]
  ...
  [244 227 206]
  [244 227 206]
  [245 228 207]]

 ...

 [[204 207 198]
  [198 201 192]
  [188 191 182]
  ...
  [188 162 146]
  [185 159 143]
  [185 159 143]]

 [[202 205 196]
  [193 196 187]
  [182 185 176]
  ...
  [188 162 146]
  [185 159 143]
  [184 158 142]]

 [[199 202 193]
  [190 193 184]
  [181 184 175]
  ...
  [187 161 145]
  [185 159 143]
  [185 159 143]]]


In [26]:
img = cv2.imread(r"D:\Project\project\Face_Recognition\ViaksKasaudhan\vikas1.jpeg")
re_img = cv2.resize(img,(500,400))
h = np.hstack((re_img,re_img))
cv2.imshow("vikas",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
img = cv2.imread(r"D:\Project\project\Face_Recognition\ViaksKasaudhan\vikas1.jpeg")
re_img = cv2.resize(img,(500,400))
v = np.vstack((re_img,re_img))
cv2.imshow("vikas",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [36]:
img = cv2.imread(r"D:\Project\project\Face_Recognition\ViaksKasaudhan\vikas1.jpeg")
re_img = cv2.resize(img,(350,350))
h = np.hstack((re_img,re_img,re_img))
v = np.vstack((h,h))
cv2.imshow("vikas",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
import os

In [40]:
list_name = os.listdir(r"D:\Project\project\Face_Recognition\ViaksKasaudhan")
list_name

['vikas1.jpeg',
 'vikas10.jpg',
 'vikas11.jpg',
 'vikas12.jpg',
 'vikas13.jpg',
 'vikas2.jpg',
 'vikas3.jpg',
 'vikas4.jpg',
 'vikas5.jpg',
 'vikas6.jpg',
 'vikas7.jpg',
 'vikas8.jpg',
 'vikas9.jpg']

In [44]:
list_name = os.listdir(r"D:\Project\project\Face_Recognition\ViaksKasaudhan")
for name in list_name:
    path = r"D:\\Project\\project\\Face_Recognition\\ViaksKasaudhan"
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img,(350,350))
    cv2.imshow('vikas',img)
    # cv2.waitKey(2000)   ## auto slide show
    cv2.waitKey(0)      ## slide show
cv2.destroyAllWindows()

### Read and Show Image ( imread(), imshow() )

In [47]:
import cv2

In [53]:
img = cv2.imread("vikas1.jpg")     ## rgb (0-255, 0-255, 0-255)
print(img.shape)

(1186, 1599, 3)


In [57]:
img = cv2.imread("vikas1.jpg")
print(img.shape)
img = cv2.resize(img,(350,350))
cv2.imshow('vikas',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


# (1186, 1599, 3) ->3 represent the number of channel

(1186, 1599, 3)


In [59]:
## RGB (color mode) -> it is default flag

img = cv2.imread("vikas1.jpg",1)
print(img.shape)
img = cv2.resize(img,(350,350))
cv2.imshow('vikas',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1186, 1599, 3)


In [61]:
## grayscale (blacken-white)

img = cv2.imread("vikas1.jpg",0)
print(img.shape)
img = cv2.resize(img,(350,350))
cv2.imshow('vikas',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1186, 1599)


In [63]:
## alpha channel

img = cv2.imread("vikas1.jpg",-1)
print(img.shape)
img = cv2.resize(img,(350,350))
cv2.imshow('vikas',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1186, 1599, 3)


### Text Over a Image

In [ ]:
#(img, text, org, fontFace, fontScale,color[,thickness[, lineType[,bottomLeftOrigin]]])

In [68]:
import cv2

In [96]:
img_get = cv2.imread(r"D:\Project\project\Face_Recognition\ViaksKasaudhan\vikas1.jpeg")
img_get = cv2.resize(img_get,(400,400))


txt = cv2.putText(
    img = img_get,
    text = "Vikas Kasaudhan",
    org = (50,50),
    fontFace = cv2.FORMATTER_FMT_MATLAB,
    fontScale = 2,
    color = (255,0,0),
    thickness = 2,
    lineType = cv2.LINE_8,
    bottomLeftOrigin = False
)


txt = cv2.putText(
    img = img_get,
    text = "Vikas Kasaudhan",
    org = (50,50),
    fontFace = cv2.FORMATTER_FMT_MATLAB,
    fontScale = 2,
    color = (0,0,255),
    thickness = 2,
    lineType = cv2.LINE_8,
    bottomLeftOrigin = True
)

cv2.imshow('vikas',txt)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Draw Line and Box on Image

In [128]:
import cv2

In [129]:
old_img = cv2.imread("vikas2.jpeg")
old_img = cv2.resize(old_img,(400,400))

new_img = cv2.line(img = old_img, pt1=(180,140), pt2=(300,140), color = (0,255,0), thickness = 2, lineType=4)
cv2.imshow("vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [142]:
old_img = cv2.imread("vikas2.jpeg")
old_img = cv2.resize(old_img,(400,400))

new_img = cv2.rectangle(img = old_img, pt1=(150,100), pt2=(300,300), color = (0,255,0), thickness = 2, lineType=4)
cv2.imshow("vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [156]:
old_img = cv2.imread("vikas2.jpeg")
old_img = cv2.resize(old_img,(400,400))

new_img = cv2.putText(img = old_img,text = 'Vikas Kasaudhan',org = (100,90),fontFace=cv2.FaceRecognizerSF_FR_NORM_L2,fontScale=2,color=(0,255,0),thickness=2,lineType=cv2.LINE_4)
new_img = cv2.rectangle(img = old_img, pt1=(150,100), pt2=(300,300), color = (0,255,0), thickness = 2, lineType=4)
cv2.imshow("vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Draw Circle and Ellipse on Image

In [205]:
import cv2

In [211]:
old_img = cv2.imread("vikas2.jpeg")
new_img = cv2.resize(old_img,(400,400))

new_img = cv2.putText(img = new_img,text = 'Vikas Kasaudhan',org = (100,90),fontFace=cv2.FaceRecognizerSF_FR_NORM_L2,fontScale=2,color=(0,255,0),thickness=2,lineType=cv2.LINE_4)
new_img = cv2.circle(img=new_img,center=(220,210),radius=80,color=(0,255,0),thickness=-1,lineType=cv2.LINE_8)

cv2.imshow("Vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [217]:
old_img = cv2.imread("vikas2.jpeg")
new_img = cv2.resize(old_img,(400,400))

new_img = cv2.putText(img = new_img,text = 'Vikas Kasaudhan',org = (100,90),fontFace=cv2.FaceRecognizerSF_FR_NORM_L2,fontScale=2,color=(0,255,0),thickness=2,lineType=cv2.LINE_4)
new_img = cv2.ellipse(img=new_img,center=(230,210),axes=(60,90),angle=0,startAngle=0,endAngle=360,color=(217, 222, 203),thickness=-1,lineType=cv2.LINE_8)

cv2.imshow("Vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Draw Polygon on Image

In [224]:
import cv2
import numpy as np

In [246]:
img = cv2.imread("vikas2.jpeg")
new_img = cv2.resize(img,(400,400))


new_img = cv2.polylines(img=new_img,
                        pts=[np.array([[150,120],
                [180,50],
                [300,120],
                [200,250],
                [80,250]])]
                       ,thickness=2,lineType=cv2.LINE_8 ,color=(0,255,0),isClosed=True)

cv2.imshow("Vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Arithmetic Operation on Images

In [249]:
import cv2
import numpy as np

In [266]:
img1 = cv2.imread("vikas1.jpg")
img2 = cv2.imread("vikas2.jpeg")

img1 = cv2.resize(img1,(400,400))
img2 = cv2.resize(img2,(400,400))

new_img = cv2.addWeighted(img1,1,img2,0.2,5)
cv2.imshow("Vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [268]:
img1 = cv2.imread("vikas1.jpg")
img2 = cv2.imread("vikas2.jpeg")

img1 = cv2.resize(img1,(400,400))
img2 = cv2.resize(img2,(400,400))

new_img = cv2.subtract(img1,img2)
cv2.imshow("Vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Bitwise Operation on images

In [273]:
import cv2
import numpy as np

In [287]:
img1 = cv2.imread("images1.png")
img2 = cv2.imread("images2.png")

img1 = cv2.resize(img1,(400,400))
img2 = cv2.resize(img2,(400,400))

new_img = cv2.bitwise_and(img1,img2)
# new_img = cv2.bitwise_or(img1,img2)
#new_img = cv2.bitwise_not(img1)
# new_img = cv2.bitwise_xor(img1,img2)

h = np.hstack((img1,img2,new_img))

cv2.imshow("Vikas",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [289]:
img1 = cv2.imread("images1.png")

img1 = cv2.resize(img1,(400,400))

new_img = cv2.bitwise_not(img1)

h = np.hstack((img1,new_img))

cv2.imshow("Vikas",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [291]:
img1 = cv2.imread("vikas1.jpg")

img1 = cv2.resize(img1,(400,400))

new_img = cv2.bitwise_not(img1)

h = np.hstack((img1,new_img))

cv2.imshow("Vikas",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [297]:
img1 = cv2.imread("vikas1.jpg")
img2 = cv2.imread("vikas2.jpeg")

img1 = cv2.resize(img1,(400,400))
img2 = cv2.resize(img2,(400,400))

#new_img = cv2.bitwise_and(img1,img2)
#new_img = cv2.bitwise_or(img1,img2)
new_img = cv2.bitwise_xor(img1,img2)

h = np.hstack((img1,img2,new_img))

cv2.imshow("Vikas",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Edge Detection

In [336]:
img = cv2.imread("vikas1.jpg")
print(img.shape)

img = cv2.resize(img,(400,400))

new_img = cv2.Canny(img,400,200,apertureSize=5,L2gradient=True)
print(new_img.shape)


cv2.imshow("Vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1186, 1599, 3)
(400, 400)


### Scaling and Rotation of images

In [339]:
import cv2

In [349]:
ori_img = cv2.imread("vikas1.jpg")
new_img = cv2.resize(ori_img,(500,500))
w,h = new_img.shape[0],new_img.shape[1]

m = cv2.getRotationMatrix2D((w/2,h/2),180,1)
fin_img = cv2.warpAffine(new_img,m,(h,w))

h = np.hstack((new_img,fin_img))
cv2.imshow("vikas",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Image Blurring 

In [352]:
import cv2
import numpy as np

In [356]:
ori_img = cv2.imread("vikas1.jpg")
new_img = cv2.resize(ori_img,(300,300))

g = cv2.GaussianBlur(new_img,(5,5),0)
m = cv2.medianBlur(new_img,5)
b = cv2.bilateralFilter(new_img,10,100,100)

h = np.hstack((new_img,g,m,b))
cv2.imshow("vikas",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Imwrite Function (saving images)

In [365]:
ori_img1 = cv2.imread("vikas1.jpg")
ori_img2 = cv2.imread("vikas2.jpeg")
ori_img3 = cv2.imread("vikas3.jpg")
ori_img4 = cv2.imread("vikas8.jpg")

new_img1 = cv2.resize(ori_img1,(300,300))
new_img2 = cv2.resize(ori_img2,(300,300))
new_img3 = cv2.resize(ori_img3,(300,300))
new_img4 = cv2.resize(ori_img4,(300,300))

h1 = np.hstack((new_img1,new_img2))
h2 = np.hstack((new_img3,new_img4))
v = np.vstack((h1,h2))

cv2.imwrite("Kasaudhan.png",v)

cv2.imshow("vikas",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Makeborder of Images

In [1]:
import cv2
import numpy as np

In [2]:
ori_img = cv2.imread("vikas1.jpg")
new_img = cv2.resize(ori_img,(300,300))

# img1 = cv2.copyMakeBorder(new_img,20,20,20,20,cv2.BORDER_CONSTANT,None, value=2)
img1 = cv2.copyMakeBorder(new_img,20,20,20,20,cv2.BORDER_WRAP,None, value=10)

img1 = cv2.resize(img1,(300,300))


h = np.hstack((new_img,img1))
cv2.imshow("vikas",h)
cv2.waitKey(0)
cv2.destroyAllWindows()