### creating Blank Image

In [2]:
import cv2
import numpy as np

In [4]:
img = cv2.imread("vikas1.jpg")
img = cv2.resize(img,(500,500))

new_img = np.ones((500,500,3),np.uint8)*255

cv2.imshow("vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [137 147 134]
  [173 182 171]
  [168 182 176]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [147 151 140]
  [189 196 186]
  [151 163 157]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [167 163 159]
  [149 152 147]
  [191 201 194]]

 ...

 [[173 177 193]
  [192 197 212]
  [191 194 206]
  ...
  [106 125 157]
  [105 123 156]
  [106 123 156]]

 [[172 166 171]
  [142 135 140]
  [152 141 144]
  ...
  [103 122 155]
  [104 122 155]
  [105 122 155]]

 [[138 120 121]
  [136 118 114]
  [132 115 109]
  ...
  [101 122 154]
  [103 124 156]
  [103 124 156]]]


In [8]:
print(new_img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [10]:
img = cv2.imread("vikas1.jpg")
img = cv2.resize(img,(500,500))

new_img = np.zeros((500,500,3),np.uint8)*255

cv2.imshow("vikas",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Color Picker

In [1]:
import cv2
import numpy as np

In [2]:
def wscube(x):
    pass

In [4]:
img = np.zeros((500,500,3),np.uint8)*255
cv2.namedWindow("color")

cv2.createTrackbar("R","color",0,255,wscube)
cv2.createTrackbar("G","color",0,255,wscube)
cv2.createTrackbar("B","color",0,255,wscube)

while True:
    cv2.imshow("color",img)
    if cv2.waitKey(1) & 0xff==ord("p"):
        break

    r = cv2.getTrackbarPos("R","color")
    g = cv2.getTrackbarPos("G","color")
    b = cv2.getTrackbarPos("B","color")

    img[:] = [b,g,r]


cv2.destroyAllWindows()

### getTrackbarPos()

In [1]:
import cv2
import numpy as np

In [3]:
def wscube(x):
    pass

In [4]:
img = np.zeros((500,500,3),np.uint8)*255
cv2.namedWindow("bar")
cv2.createTrackbar("on","bar",0,255,wscube)

while True:
    cv2.imshow("bar",img)
    if cv2.waitKey(1)  & 0xff==ord("p"):
        break
        
    on = cv2.getTrackbarPos("on","bar")
    img[:] = [0,0,on]

cv2.destroyAllWindows()

In [9]:
cv2.imshow("vikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### region of interest

In [58]:
import cv2
import numpy as np

In [68]:
img = cv2.imread("save.jpg")

crop = img[40:200,320:440]

img[40:200,440:560] = crop   ## right
img[40:200,560:680] = crop   ## right
img[40:200,200:320] = crop   ## left
img[40:200,80:200] = crop    ## left

cv2.imwrite("save.jpg",img)
cv2.imshow("vikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
import cv2

In [54]:
img = cv2.imread("save.jpg")

crop = img[40:200,320:440]

cv2.imshow("vikas1",crop)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Flip, Rotate , and Transpose

In [71]:
import cv2

In [87]:
img =  cv2.imread('vikas2.jpeg')
img = cv2.resize(img,(500,500))

# # img = cv2.flip(img,1)   ## y axis
# img = cv2.flip(img,0)     ## x axis
# img = cv2.flip(img,-1)    ## x , y axis

# img = cv2.rotate(img,cv2.ROTATE_180)

img = cv2.transpose(img)

cv2.imshow("vikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### saving video

In [94]:
import cv2

In [108]:
cap = cv2.VideoCapture(0)

f = cv2.VideoWriter_fourcc(*"XVID")
out = cv2.VideoWriter("demo.mp4",f,40.0,(640,360))

while cap.isOpened():
    r, frame = cap.read()
    if r == True:
        frame = cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow("vikas",frame)
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else:
        break

cap.release()
out.release()
cv2.destroyAllWindows()

In [ ]:
cap = cv2.VideoCapture(0)

f = cv2.VideoWriter_fourcc(*"XVID")
out = cv2.VideoWriter("demo.mp4",f,40.0,(640,360),0)

while cap.isOpened():
    r, frame = cap.read()
    if r == True:
        frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        frame = cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow("vikas",frame)
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else:
        break

cap.release()
out.release()
cv2.destroyAllWindows()

### Color Spaces
* RGB
* CMYK (cyan,magenta,yellow,black)
* HSV (Hue, saturation, value)

In [130]:
import cv2
import numpy as np

In [132]:
img = cv2.imread("images.jpeg")
img = cv2.resize(img,(500,400))

def wscube(a):
    pass

cv2.namedWindow("demo")
cv2.createTrackbar("lb","demo",0,255,wscube)
cv2.createTrackbar("lg","demo",0,255,wscube)
cv2.createTrackbar("lr","demo",0,255,wscube)

cv2.createTrackbar("ub","demo",0,255,wscube)
cv2.createTrackbar("ug","demo",0,255,wscube)
cv2.createTrackbar("ur","demo",0,255,wscube)

while True:
    hsv_img = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

    Lb = cv2.getTrackbarPos("lb","demo")
    Lg = cv2.getTrackbarPos("lg","demo")
    Lr = cv2.getTrackbarPos("lg","demo")
    
    Ub = cv2.getTrackbarPos("ub","demo")
    Ug = cv2.getTrackbarPos("ug","demo")
    Ur = cv2.getTrackbarPos("ur","demo")
    
    lo = np.array([Lb,Lg,Lr])
    up = np.array([Ub,Ug,Ur])
    
    masks = cv2.inRange(hsv_img,lo,up)
    
    res = cv2.bitwise_and(img,img,mask=masks)
    
    cv2.imshow("res",res)
    cv2.imshow("mask",masks)
    cv2.imshow("hsv",hsv_img)
    cv2.imshow("wscube",img)
    if cv2.waitKey(1) & 0xff==ord("p"):
        break

cv2.destroyAllWindows()

### Filter Color 

In [124]:
import cv2
import numpy as np

In [128]:
cap = cv2.VideoCapture(0)

def wscube(a):
    pass

cv2.namedWindow("demo")
cv2.createTrackbar("lb","demo",0,255,wscube)
cv2.createTrackbar("lg","demo",0,255,wscube)
cv2.createTrackbar("lr","demo",0,255,wscube)

cv2.createTrackbar("ub","demo",0,255,wscube)
cv2.createTrackbar("ug","demo",0,255,wscube)
cv2.createTrackbar("ur","demo",0,255,wscube)

while cap.isOpened():
    r, frame = cap.read()
    if r==True:
        img = cv2.resize(frame,(400,300))
        hsv_img = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
    
        Lb = cv2.getTrackbarPos("lb","demo")
        Lg = cv2.getTrackbarPos("lg","demo")
        Lr = cv2.getTrackbarPos("lg","demo")
        
        Ub = cv2.getTrackbarPos("ub","demo")
        Ug = cv2.getTrackbarPos("ug","demo")
        Ur = cv2.getTrackbarPos("ur","demo")
        
        lo = np.array([Lb,Lg,Lr])
        up = np.array([Ub,Ug,Ur])
        
        masks = cv2.inRange(hsv_img,lo,up)
        
        res = cv2.bitwise_and(img,img,mask=masks)
        
        cv2.imshow("res",res)
        cv2.imshow("mask",masks)
        cv2.imshow("hsv",hsv_img)
        cv2.imshow("wscube",img)
        if cv2.waitKey(1) & 0xff==ord("p"):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

### Perspective Transformation

In [135]:
import cv2
import numpy as np

In [143]:
img = cv2.imread("subscribe.png")

# cv2.circle(img,(126,182),4,(0,0,255),-1)
# cv2.circle(img,(485, 182),4,(0,0,255),-1)
# cv2.circle(img,(57 , 658),4,(0,0,255),-1)
# cv2.circle(img,(614, 634),4,(0,0,255),-1)

print(img.shape)

cv2.imshow("vikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(751, 621, 3)


In [141]:
src1 = np.float32([[26, 182],[485, 182],[57 , 658],[614, 634]])
src1

array([[ 26., 182.],
       [485., 182.],
       [ 57., 658.],
       [614., 634.]], dtype=float32)

In [145]:
img = cv2.imread("subscribe.png")
w, h = (621,751)

src1 = np.float32([[26, 182],[485, 182],[57 , 658],[614, 634]])
dst1 = np.float32([[0,0],[w,0],[0,h],[w,h]])
m = cv2.getPerspectiveTransform(src1,dst1)
new_img = cv2.warpPerspective(img,m,(w,h))

cv2.imshow("ws",new_img)
cv2.imshow("vikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 126, 182
# 485, 182
# 57 , 658
# 614, 634

## Threshold
* simple thresholding
* otsu's
* adaptive

In [2]:
import cv2

In [20]:
img = cv2.imread("coin.png")
img = cv2.resize(img,(700,400))

_, th = cv2.threshold(img,150,255,cv2.THRESH_BINARY)

cv2.imshow("threshold",th)
cv2.imshow("vikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [48]:
img = cv2.imread("parent.png")
img = cv2.resize(img,(700,400))

img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# _, th = cv2.threshold(img,120,255,cv2.THRESH_BINARY)
# _, th = cv2.threshold(img,120,255,cv2.THRESH_BINARY_INV)
_, th = cv2.threshold(img,120,255,cv2.THRESH_TOZERO)

cv2.imshow("threshold",th)
cv2.imshow("vikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Ostu's thresholding

In [63]:
import cv2

In [73]:
img = cv2.imread("leave.png")
img = cv2.resize(img,(700,500))
img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


_,thr = cv2.threshold(img,200,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)

cv2.imshow("vikas",img)
cv2.imshow("vikas1",thr)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Histogram Equalization

### CLAHE (Contrast Limited Adaptive Histogram Equalizer)

In [79]:
import cv2

In [93]:
img = cv2.imread("histogram-equalize.jpg")

gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

hist = cv2.calcHist([img],[0],None,[255],[0,255])
eq = cv2.equalizeHist(gry)
hist = cv2.calcHist([eq],[0],None,[255],[0,255])

# plt.plot(eq,c = 'red')
# plt.plot(hist)
# plt.show()

cv2.imshow("vikas1",eq)
cv2.imshow("ikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [95]:
img = cv2.imread("Screenshot 2025-10-01 155918.png")

gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

hist = cv2.calcHist([img],[0],None,[255],[0,255])
eq = cv2.equalizeHist(gry)
hist = cv2.calcHist([eq],[0],None,[255],[0,255])

cl = cv2.createCLAHE(clipLimit=1,tileGridSize=(8,8))
f = cl.apply(gry)

# plt.plot(eq,c = 'red')
# plt.plot(hist)
# plt.show()

cv2.imshow("wscube",f)
cv2.imshow("vikas1",eq)
cv2.imshow("ikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Mouse Event

In [102]:
import cv2
import numpy as np

In [104]:
def python(event,x,y,f,p):
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img,(x,y),5,(0,0,255),4)
    elif event == cv2.EVENT_RBUTTONDOWN:
        cv2.rectangle(img,(x,y),(x+20,y+20),(255,0,0),4)

In [108]:
cv2.namedWindow("wscube")
img = np.ones((600,600,3),np.uint8)*255
cv2.setMouseCallback("wscube",python)

while True:
    cv2.imshow("wscube",img)
    if cv2.waitKey(25) & 0xff==ord("p"):
        break

cv2.destroyAllWindows()

In [100]:
cv2.imshow("vikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### image contour

In [115]:
import cv2

In [121]:
img = cv2.imread("crome.png")
img1 = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

r , thr = cv2.threshold(img1,100,255,cv2.THRESH_BINARY)

cv2.imshow("vk",thr)
cv2.imshow("vikas",img)
cv2.waitKey(0)
cv2.destroyAllWindows()